/*
 * EUVD API
 *
 * API for querying recent vulnerabilities from the ENISA EUVD database.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Advisory {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "datePublished", skip_serializing_if = "Option::is_none")]
    pub date_published: Option<String>,
    #[serde(rename = "dateUpdated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    #[serde(rename = "baseScore", skip_serializing_if = "Option::is_none")]
    pub base_score: Option<f32>,
    #[serde(rename = "references", skip_serializing_if = "Option::is_none")]
    pub references: Option<String>,
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::AdvisorySource>>,
    #[serde(rename = "advisoryProduct", skip_serializing_if = "Option::is_none")]
    pub advisory_product: Option<Vec<models::AdvisoryAdvisoryProductInner>>,
    #[serde(rename = "enisaIdAdvisories", skip_serializing_if = "Option::is_none")]
    pub enisa_id_advisories: Option<Vec<models::AdvisoryEnisaIdAdvisoriesInner>>,
    #[serde(rename = "vulnerabilityAdvisory", skip_serializing_if = "Option::is_none")]
    pub vulnerability_advisory: Option<Vec<models::AdvisoryVulnerabilityAdvisoryInner>>,
}

impl Advisory {
    pub fn new() -> Advisory {
        Advisory {
            id: None,
            description: None,
            summary: None,
            date_published: None,
            date_updated: None,
            base_score: None,
            references: None,
            aliases: None,
            source: None,
            advisory_product: None,
            enisa_id_advisories: None,
            vulnerability_advisory: None,
        }
    }
}

