/*
 * EUVD API
 *
 * API for querying recent vulnerabilities from the ENISA EUVD database.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdvisoryAdvisoryProductInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "product", skip_serializing_if = "Option::is_none")]
    pub product: Option<Box<models::NestedProduct>>,
}

impl AdvisoryAdvisoryProductInner {
    pub fn new() -> AdvisoryAdvisoryProductInner {
        AdvisoryAdvisoryProductInner {
            id: None,
            product: None,
        }
    }
}

