/*
 * EUVD API
 *
 * API for querying recent vulnerabilities from the ENISA EUVD database.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NestedVendor {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl NestedVendor {
    pub fn new() -> NestedVendor {
        NestedVendor {
            name: None,
        }
    }
}

